const SIGN_IN = 'SIGN_IN'
const LOG_OUT = 'LOG_OUT'
const DELETE_ACCOUNT = 'DELETE_ACCOUNT'
const SET_ID = 'SET_ID'

const PLAY_SOUND = 'PLAY_SOUND'
const PAUSE_SOUND = 'PAUSE_SOUND'
const STOP_SOUND = 'STOP_SOUND'

const SET_THEME = 'SET_THEME'
const SET_PRIMARY_COLOR = 'SET_PRIMARY_COLOR'

const CREATE_PROJECT = 'CREATE_PROJECT'
const UPDATE_PROJECT = 'UPDATE_PROJECT'
const DELETE_PROJECT = 'DELETE_PROJECT'

const SET_SELECTED_PROJECT = 'SET_SELECTED_PROJECT'

const SET_USER_MONEY_PREFERENCES = 'SET_USER_MONEY_PREFERENCES'
const SET_TIME_PREFERENCES = 'SET_TIME_PREFERENCES'

export const ActionTypes = {
  SIGN_IN,
  LOG_OUT,
  SET_ID,
  DELETE_ACCOUNT,
  PLAY_SOUND,
  PAUSE_SOUND,
  STOP_SOUND,
  SET_THEME,
  SET_PRIMARY_COLOR,
  CREATE_PROJECT,
  UPDATE_PROJECT,
  DELETE_PROJECT,
  SET_SELECTED_PROJECT,
  SET_USER_MONEY_PREFERENCES,
  SET_TIME_PREFERENCES
}
